import { TransactionDetails } from "./TransactionDetails";

export type SignedTransactionDetails = {
  /**
   * Session ID associated with this transaction, used to link the transaction
   * to a specific session between a client and a merchant.
   */
  sessionId: string;

  /**
   * Transaction details including the amount, merchant ID, receiver's USDC account,
   * DAO's USDC account, and the state account involved in the transaction.
   */
  transactionDetails: TransactionDetails;

  /**
   * Client's public key, identifying the client within the transaction.
   */
  clientPublicKey: string;

  /**
   * Client's signature, proving the client's agreement to the transaction.
   * This is the cryptographic signature generated by the client, signing the transaction details.
   */
  clientSignature: string;

  /**
   * (Optional) Service wallet's public key. This is included if the service wallet
   * is also signing the transaction, typically to cover gas fees for the client.
   */
  serviceWalletPublicKey?: string;

  /**
   * (Optional) Service wallet's signature. This is the cryptographic signature generated
   * by the service wallet, signing the transaction details to cover gas fees.
   * This field is optional and only included if the service wallet is involved.
   */
  serviceWalletSignature?: string;
};
