# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - transactions-service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://cryptomapp.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_aef2d9ddd42d4ee4a897c2c80a36f097 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_6527f4e729cd451fbe220570685e5c0a }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: cryptomapp.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_aef2d9ddd42d4ee4a897c2c80a36f097 }}/mcr.microsoft.com/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'transactions-service'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_5e88aa209daf469ebe0beeb04ca507f4 }}
        images: 'cryptomapp.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_aef2d9ddd42d4ee4a897c2c80a36f097 }}/mcr.microsoft.com/appsvc/staticsite:${{ github.sha }}'